CREATE TABLE USUARIO (
  ID_USUARIO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE       VARCHAR2(50),
  EMAIL        VARCHAR2(100),
  PASSWORD     VARCHAR2(30)
);


CREATE TABLE PRODUCTO (
  ID_PRODUCTO  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE       VARCHAR2(100),
  PRECIO       NUMBER(10,2),
  STOCK        NUMBER
);


CREATE TABLE PEDIDO (
  ID_PEDIDO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO   NUMBER,
  FECHA_PEDIDO DATE DEFAULT SYSDATE,
  CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE PEDIDO_DETALLE (
  ID_PEDIDO    NUMBER,
  ID_PRODUCTO  NUMBER,
  CANTIDAD     NUMBER,
  CONSTRAINT PK_PEDIDO_DETALLE PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
  CONSTRAINT FK_DETALLE_PED FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
  CONSTRAINT FK_DETALLE_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
-- se me olvido a la tabla pedido ponerle un total tienes que agregarlo
ALTER TABLE PEDIDO ADD (TOTAL NUMBER(14,2) DEFAULT 0);

-- para que el email no se vuelva a repetir

ALTER TABLE USUARIO
ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL);


--los inserts

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD)
VALUES ('Ana', 'ana@mail.com', '1234');

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD)
VALUES ('Luis', 'luis@mail.com', 'abcd');

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD)
VALUES ('Marta', 'marta@mail.com', 'pass1');

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD)
VALUES ('Pedro', 'pedro@mail.com', 'pass2');


INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK)
VALUES ('Tomate', 1000, 50);

INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK)
VALUES ('Lechuga', 800, 30);

INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK)
VALUES ('Zanahoria', 600, 40);

INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK)
VALUES ('Maceta', 2500, 20);


INSERT INTO PEDIDO (ID_USUARIO) VALUES (15);  -- Pedido de Ana
INSERT INTO PEDIDO (ID_USUARIO) VALUES (16);  -- Pedido de Luis
INSERT INTO PEDIDO (ID_USUARIO) VALUES (17);  -- Pedido de Marta
INSERT INTO PEDIDO (ID_USUARIO) VALUES (18);  -- Pedido de Pedro



INSERT INTO PEDIDO_DETALLE (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (1, 1, 2);  

INSERT INTO PEDIDO_DETALLE (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (2, 2, 1);  

INSERT INTO PEDIDO_DETALLE (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (3, 3, 5);  

INSERT INTO PEDIDO_DETALLE (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (4, 4, 1); 
