--trigger para validar stock antes de vender

CREATE OR REPLACE TRIGGER trg_valida_stock
BEFORE INSERT ON PEDIDO_DETALLE
FOR EACH ROW
DECLARE v_stock NUMBER;
BEGIN
  SELECT STOCK INTO v_stock FROM PRODUCTO WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
  IF v_stock < :NEW.CANTIDAD THEN
    RAISE_APPLICATION_ERROR(-20001, 'Stock insuficiente');
  END IF;
END;
/

--trigger para devolver stock

CREATE OR REPLACE TRIGGER trg_repone_stock
AFTER DELETE ON PEDIDO_DETALLE
FOR EACH ROW
BEGIN
  UPDATE PRODUCTO SET STOCK = STOCK + :OLD.CANTIDAD
  WHERE ID_PRODUCTO = :OLD.ID_PRODUCTO;
END;
/
